#!/bin/bash

set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
source "${ROOT}/script/lib/ui.sh"

usage() {
  cat <<USAGE >&2
usage: $0 [-h|--help] <command>

COMMANDS:
  build          Build static assets
  start          Start dev server
  test           Run tests
  bash           Open bash console in dashbaordv2 dir with deps

OPTIONS:
  -h, --help    Show this message
USAGE
}

main() {
  if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
    usage
    exit
  fi

  case "$1" in
    build)
      nodejs_command "build"
      ;;
    start)
      nodejs_command "start"
      ;;
    test)
      nodejs_command "test"
      ;;
    bash)
      bash
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}

bash() {
  local flynn_host="${ROOT}/build/bin/flynn-host"
  local builder_image="${ROOT}/build/image/dashboardv2-base.json"

  "${flynn_host}" run \
    --bind    "${ROOT}:${ROOT}" \
    --limits  "temp_disk=1G" \
    --workdir "${ROOT}/dashboardv2" \
    --hostnet \
    "${builder_image}" \
    bash
}

nodejs_command() {
  local cmd=$1

  local flynn_host="${ROOT}/build/bin/flynn-host"
  local builder_image="${ROOT}/build/image/dashboardv2-base.json"

  "${flynn_host}" run \
    --bind    "${ROOT}:${ROOT}" \
    --limits  "temp_disk=1G" \
    --workdir "${ROOT}/dashboardv2" \
    --hostnet \
    "${builder_image}" \
    yarn run $cmd
}

main $@
